apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app }}-deployment
  labels:
    app: {{ .Values.app }}-k8s
spec:
  replicas: 2
  selector:
    matchLabels:
      project: {{ .Values.app }}
  template:
    metadata:
      labels:
        project: {{ .Values.app }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: {{ .Values.app }}-web
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
          - containerPort: 80

