apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app }}-deployment
  labels:
    app: {{ .Values.app }}-k8s
spec:
  replicas: 2
  selector:
    matchLabels:
      project: {{ .Values.app }}
  template:
    metadata:
      labels:
        project: {{ .Values.app }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "80"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: {{ .Values.app }}-web
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
          - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.app }}-hpa
  labels:
    app: {{ .Values.app }}-k8s
  spec:
    scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: {{ .Values.app }}-deployment
    minReplicas: 2
    maxReplicas: 5
    metrics:
      - type: Resources
        resourse:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 75
  
          
        

